
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
import os, json, hashlib, time
from datetime import datetime, timezone

def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

def _collect_artifacts(out_dir):
    artifacts = []
    for root, _, files in os.walk(out_dir):
        for f in files:
            p = os.path.join(root, f)
            rel = os.path.relpath(p, out_dir)
            artifacts.append((rel, p, _sha256(p)))
    artifacts.sort()
    return artifacts

def export_pdf(ctx, out_pdf_path):
    """
    Build a simple investigation report PDF (A4, 1–3 pages) with:
      - Title and context
      - Timeline (start/end UTC)
      - Hashes of artifacts in output directory
      - IOC summary if ctx contains 'iocs'
    ctx: dict with keys like:
      - case_id (str)
      - started_at / finished_at (RFC3339 string or epoch)
      - out_dir (str)  # folder with artifacts to hash list
      - iocs (list[dict]) optional
    """
    out_dir = ctx.get("out_dir")
    case_id = ctx.get("case_id","N/A")
    started_at = ctx.get("started_at")
    finished_at = ctx.get("finished_at")
    iocs = ctx.get("iocs") or []

    # Normalize times
    def norm_ts(v):
        if v is None:
            return None
        if isinstance(v, (int, float)):
            return datetime.fromtimestamp(v, tz=timezone.utc).isoformat()
        if isinstance(v, str):
            return v
        return str(v)
    started_at = norm_ts(started_at)
    finished_at = norm_ts(finished_at)

    c = canvas.Canvas(out_pdf_path, pagesize=A4)
    W, H = A4

    # Header
    c.setTitle(f"Scam_GEO Banking Report – {case_id}")
    c.setAuthor("Scam_GEO Banking")
    c.setSubject("Investigation Report")
    y = H - 20*mm
    c.setFont("Helvetica-Bold", 18)
    c.drawString(20*mm, y, "Scam_GEO Banking – Investigation Report")
    y -= 10*mm
    c.setFont("Helvetica", 11)
    c.drawString(20*mm, y, f"Case ID: {case_id}")
    y -= 6*mm
    c.drawString(20*mm, y, f"Started (UTC): {started_at or '-'}")
    y -= 6*mm
    c.drawString(20*mm, y, f"Finished (UTC): {finished_at or '-'}")
    y -= 10*mm

    # IOC summary
    if iocs:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(20*mm, y, "IOC Summary")
        y -= 7*mm
        c.setFont("Helvetica", 10)
        MAX = 12
        shown = 0
        for ioc in iocs:
            if y < 25*mm:
                c.showPage(); y = H - 20*mm
            t = ioc.get("type","?").upper()
            v = ioc.get("value","")
            s = ioc.get("score")
            line = f"- {t}: {v[:90]}{'…' if len(v)>90 else ''}  (score: {s if s is not None else '-'})"
            c.drawString(20*mm, y, line)
            y -= 5*mm
            shown += 1
            if shown >= 60:
                break
        if len(iocs) > shown:
            if y < 25*mm: c.showPage(); y = H - 20*mm
            c.drawString(20*mm, y, f"... and {len(iocs)-shown} more")
            y -= 5*mm
        y -= 5*mm

    # Artifacts + hashes
    if out_dir and os.path.isdir(out_dir):
        artifacts = _collect_artifacts(out_dir)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(20*mm, y, "Artifacts (SHA-256)")
        y -= 7*mm
        c.setFont("Helvetica", 9)
        for rel, p, h in artifacts[:120]:
            if y < 25*mm:
                c.showPage(); y = H - 20*mm; c.setFont("Helvetica", 9)
            txt = f"{rel}  ::  {h[:16]}…{h[-8:]}"
            c.drawString(20*mm, y, txt)
            y -= 4.5*mm

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(20*mm, 12*mm, "Auto-generated by Scam_GEO Banking. Times in UTC (RFC3339).")
    c.save()
    return out_pdf_path
